apiVersion: apps/v1
kind: Deployment
metadata:
  name: excelidraw-http-backend
  namespace: excelidraw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excelidraw-http-backend
  template:
    metadata:
      labels:
        app: excelidraw-http-backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:15-alpine
          command: 
            - sh
            - -c
            - |
              until pg_isready -h excelidraw-postgres -p 5432 -U $POSTGRES_USER; do
                echo "Waiting for postgres..."
                sleep 2
              done
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: excelidraw-database-secret
                  key: POSTGRES_USER
      containers:
        - name: http-backend
          # TODO: Replace with your actual Docker image
          image: aabhii/excelidraw-http-backend:amd64-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: excelidraw-database-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: excelidraw-app-secret
                  key: JWT_SECRET
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: excelidraw-config
                  key: HTTP_PORT
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: excelidraw-http-backend
  namespace: excelidraw
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: excelidraw-http-backend
  ports:
  - port: 3001
    targetPort: 3001