apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: excelidraw-postgres-pvc
  namespace: excelidraw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # Option 1: WaitForFirstConsumer (standard-rwo)
  # storageClassName: standard-rwo
  
  # Option 2: Immediate provisioning (standard)
  storageClassName: standard