apiVersion: apps/v1
kind: Deployment
metadata:
  name: excelidraw-ws-backend
  namespace: excelidraw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excelidraw-ws-backend
  template:
    metadata:
      labels:
        app: excelidraw-ws-backend
    spec:
      containers:
        - name: ws-backend
          # TODO: Replace with your actual Docker image
          image: aabhii/excelidraw-ws-backend:amd64-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: excelidraw-database-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: excelidraw-app-secret
                  key: JWT_SECRET
            - name: WS_PORT
              valueFrom:
                configMapKeyRef:
                  name: excelidraw-config
                  key: WS_PORT
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: excelidraw-ws-backend
  namespace: excelidraw
spec:
  selector:
    app: excelidraw-ws-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP